### ISSUE TITLE
equo: Crashing on autocomplete

### ISSUE THREAD

**Issue by m-lawliet** [Sabayon/entropy#73]
Hello,

Using tab autocomplete for command:
`equo security oscheck --assimilate`
I got a crash after pressing tab just one another time.
I don't know if issue is related to this specific combination of command/options, I have not done further tests.
Here is the crash report i got:

> ☢ Hi. My name is Bug Reporter. I am sorry to inform you that the program crashed. Well, you know, shit happens.
> ☢ But there's something you could do to help me to be a better application.
> ☢ -- BUT, DO NOT SUBMIT THE SAME REPORT MORE THAN ONCE --
> ☢ Now I am showing you what happened. Don't panic, I'm here to help you.
> Traceback (most recent call last):
>   File "/usr/bin/equo", line 18, in <module>
>     main()
>   File "/usr/lib/entropy/client/solo/main.py", line 311, in main
>     cmd_obj.bashcomp(last_arg)
>   File "/usr/lib/entropy/client/solo/commands/security.py", line 210, in bashcomp
>     last_arg, outcome, self._commands)
>   File "/usr/lib/entropy/client/solo/commands/command.py", line 195, in _hierarchical_bashcomp
>     _commands = commands[item]
> KeyError: u'--assimilate'
> ☢ 
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/entropy/client/solo/main.py", line 167, in handle_exception
>     rc = _text.ask_question(ask_msg)
>   File "/usr/lib/entropy/lib/entropy/output.py", line 815, in ask_question
>     raise KeyboardInterrupt()
> KeyboardInterrupt
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/bin/equo", line 18, in <module>
>     main()
>   File "/usr/lib/entropy/client/solo/main.py", line 311, in main
>     cmd_obj.bashcomp(last_arg)
>   File "/usr/lib/entropy/client/solo/commands/security.py", line 210, in bashcomp
>     last_arg, outcome, self._commands)
>   File "/usr/lib/entropy/client/solo/commands/command.py", line 195, in _hierarchical_bashcomp
>     _commands = commands[item]
> KeyError: u'--assimilate'
>

**Comment by Enlik** [comment]
Thanks for reporting! #75 fixes it.

**Comment by geaaru** [comment]
thanks @m-lawliet 
Fix will be available with v.320 soon.
